<?php require 'templates/header.phtml' ?>

<?php require 'templates/form_alta.phtml' ?>

<ul class="list-group">
<?php foreach($cias as $cia): ?>
    <li>
        <div class="actions">>
            <label>Nombre Compañia:</label>
            <b><?= $cia->nombre_cia ?></b> 
                <a href="mostrardetalle/<?= $cia->id_Cia ?>" type="button" class='btn btn-success ml-auto'>Mostrar Detalle</a> 
                <a href="eliminar/<?= $cia->id_Cia ?>" type="button" class='btn btn-info ml-auto'>Borrar</a>
                <a href="actualizar/<?= $cia->id_Cia ?>" type="button" class='btn btn-danger ml-auto'>Actualizar</a>            
        </div>
    </li>
<?php endforeach ?>
</ul>

<p class="mt-3"><small>Mostrando <?=$count?> Compañias</small></p>


<?php require 'templates/footer.phtml' ?>