<!-- formulario de alta de cia -->
<form action="agregar" method="POST" class="my-4">
        <div class="col-9">
            <div class="form-group">
                <label>id:</label>
                <input required name="idCia" type="text" class="form-control">
            </div>
        </div>

        <div class="col-9">
            <div class="form-group">
                <label>Nombre Compañia</label>
                <input required name="nombreCia" type="text" class="form-control">
            </div>
        </div>

        <div class="col-9">
            <div class="form-group">
                <label>Direccion:</label>
                <input required name="direccion" type="text" class="form-control">
            </div>
        </div>
    
        <div class="col-9">
            <div class="form-group">
                <label>Contacto:</label>
                <input required name="contacto" type="text" class="form-control">
            </div>
        </div>

        <div class="col-9">
            <div class="form-group">
                <label>Email:</label>
                <input required name="email" type="email" class="form-control">
            </div>
        </div>


    <button type="submit" class="btn btn-primary mt-2">Agregar</button>
</form>