<?php require 'templates/header.phtml' ?>

<?php require 'templates/form_altastro.phtml' ?>

<ul class="list-group">
<?php foreach($stros as $stro): ?>
    <li>
        <div class="actions">>
            <label> Nombre Compañia:</label>
                    <b><?= $stro->fecha_Stro ?>/</b>
                    <b><?= $stro->tipo_Stro ?>/</b>
                    <b><?= $stro->nombre_Asegurado ?>/</b>
                    <b><?= $stro->apellido_Asegurado ?>/</b>
                    <b><?= $stro->contacto_Asegurado ?>/</b>
                    <b><?= $stro->direccion_Aseg ?>/</b>
                    <b><?= $stro->localidad ?></b>
                    
                    

                <a href="eliminarstro/<?= $stro->id_Stro ?>" type="button" class='btn btn-info ml-auto'>Borrar</a>
                <a href="actualizars/<?= $stro->id_Stro ?>" type="button" class='btn btn-danger ml-auto'>Actualizar</a>
                           
        </div>
    </li>
<?php endforeach ?>
</ul>

<p class="mt-3"><small>Mostrando <?=$count?> Siniestros</small></p>


<?php require 'templates/footer.phtml' ?>